### ISSUE TITLE
listen fails with PHONE_REGISTRATION_ERROR

### ISSUE THREAD

**Issue by kittcom2** [python-ring-doorbell/python-ring-doorbell#436]
I am trying to use the CLI to listen but get an error saying that there is a phone registration error without debug and with debug I get: 

c> ring-doorbell --debug --username XXX --password XXX  listen

Ring CLI
DEBUG:ring_doorbell.ring:url: /clients_api/session
method: POST
json: {'device': {'hardware_id': 'd2bbd951-f870-5990-b7eb-d1dfca2d9167', 'metadata': {'api_version': '11', 'device_model': 'ring-doorbell:android:com.ringapp'}, 'os': 'android'}}
data: None
 extra_params: None
INFO:firebase_messaging.fcmregister:Registered with FCM
DEBUG:ring_doorbell.ring:url: /clients_api/ring_devices
method: GET
json: None
data: None
 extra_params: None
Listening, press enter to cancel
 Raised error: [WinError 10038] An operation was attempted on something that is not a socket
Traceback (most recent call last):
  File "C:\Users\Pamela\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Pamela\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Pamela\AppData\Local\Programs\Python\Python310\Scripts\ring-doorbell.exe\__main__.py", line 7, in <module>
    sys.exit(cli())
  File "C:\Users\Pamela\AppData\Local\Programs\Python\Python310\lib\site-packages\asyncclick\core.py", line 1205, in __call__
    return anyio.run(self._main, main, args, kwargs, **opts)
  File "C:\Users\Pamela\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_core\_eventloop.py", line 74, in run
    return async_backend.run(func, args, {}, backend_options)
  File "C:\Users\Pamela\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 2034, in run
    return runner.run(wrapper())
  File "C:\Users\Pamela\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 194, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\Pamela\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\Pamela\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 2022, in wrapper
    return await func(*args)
  File "C:\Users\Pamela\AppData\Local\Programs\Python\Python310\lib\site-packages\asyncclick\core.py", line 1208, in _main
    return await main(*args, **kwargs)
  File "C:\Users\Pamela\AppData\Local\Programs\Python\Python310\lib\site-packages\asyncclick\core.py", line 1120, in main
    rv = await self.invoke(ctx)
  File "C:\Users\Pamela\AppData\Local\Programs\Python\Python310\lib\site-packages\ring_doorbell\cli.py", line 89, in invoke
    _handle_exception(self._debug, exc)
  File "C:\Users\Pamela\AppData\Local\Programs\Python\Python310\lib\site-packages\ring_doorbell\cli.py", line 83, in invoke
    return await super().invoke(ctx)
  File "C:\Users\Pamela\AppData\Local\Programs\Python\Python310\lib\site-packages\asyncclick\core.py", line 1739, in invoke
    return await _process_result(await sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Pamela\AppData\Local\Programs\Python\Python310\lib\site-packages\asyncclick\core.py", line 1485, in invoke
    return await ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Pamela\AppData\Local\Programs\Python\Python310\lib\site-packages\asyncclick\core.py", line 824, in invoke
    rv = await rv
  File "C:\Users\Pamela\AppData\Local\Programs\Python\Python310\lib\site-packages\asyncclick\core.py", line 824, in invoke
    rv = await rv
  File "C:\Users\Pamela\AppData\Local\Programs\Python\Python310\lib\site-packages\ring_doorbell\cli.py", line 762, in listen
    await ainput("Listening, press enter to cancel\n")
  File "C:\Users\Pamela\AppData\Local\Programs\Python\Python310\lib\site-packages\ring_doorbell\cli.py", line 675, in ainput
    line = await loop.run_in_executor(None, functools.partial(read_with_timeout, 1))
  File "C:\Users\Pamela\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Pamela\AppData\Local\Programs\Python\Python310\lib\site-packages\ring_doorbell\cli.py", line 661, in read_with_timeout
    if select.select(
OSError: [WinError 10038] An operation was attempted on something that is not a socket

c>

**Comment by sdb9696** [comment]
It seems that the `listen` cli command does not work in windows. I can look at a fix but in the meantime you could try a linux instance if you have one.

**Comment by kittcom2** [comment]
Thanks. Just getting started with this so I was hoping it wasn't something obvious on my part.

**Comment by sdb9696** [comment]
This is now fixed in the latest `master` branch.
